# Generated by Django 4.0.5 on 2022-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
