# Generated by Django 4.0.5 on 2022-10-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_remove_category_categories_remove_teacher_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='groups',
        ),
    ]
